use std::collections::HashMap;
use std::path::Path;

use libsstadex::catalog::load_primitive_catalog;
use libsstadex::exploration::{
    CandidatePoint, PreparedSpec, PreparedSpecSource, RangeCondition, SpecOutput,
    run_prepared_expression_flow,
};
use libsstadex::primitive::build::{
    DeterministicLutBackend, PrimitiveBuildEngine, PrimitiveBuildInput, PrimitiveBuildValue,
};

fn main() -> Result<(), String> {
    let workspace_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("libsstadex should be inside the workspace");
    let primitives_dir = workspace_root.join("analoglib/primitives");

    let catalog = load_primitive_catalog(&primitives_dir).map_err(|error| format!("{error:?}"))?;
    let primitive = catalog
        .get("simplediffpair")
        .ok_or_else(|| "missing simplediffpair primitive".to_string())?;

    let build_input = PrimitiveBuildInput::new(HashMap::from([
        ("current".to_string(), PrimitiveBuildValue::Scalar(200.0e-6)),
        (
            "VINP".to_string(),
            PrimitiveBuildValue::Vector(vec![0.55, 0.65]),
        ),
        (
            "VOUTP".to_string(),
            PrimitiveBuildValue::Vector(vec![0.85, 0.95]),
        ),
        ("VTAIL".to_string(), PrimitiveBuildValue::Vector(vec![0.10])),
    ]));

    let engine = PrimitiveBuildEngine::new(DeterministicLutBackend);
    let candidate_set = engine
        .build_candidate_set_for_primitive(primitive, "xdp", &build_input)
        .map_err(|error| format!("{error:?}"))?;
    let candidate_columns = CandidatePoint::to_columns(&candidate_set.points);

    let gain_proxy = PreparedSpec::new(
        "gain_proxy",
        RangeCondition::min(0.0),
        SpecOutput::Eval,
        PreparedSpecSource::CandidateExpression {
            expression: "xdp.gm * xdp.Ro".to_string(),
        },
    );
    let table = run_prepared_expression_flow(&[], &[candidate_set.clone()], &[], &[gain_proxy])
        .map_err(|error| format!("{error:?}"))?;

    println!("Primitive: {}", primitive.name);
    println!(
        "Rows generated by declarative build: {}",
        candidate_set.points.len()
    );
    println!("Columns emitted:");
    for column in &candidate_columns {
        println!("  {}", column.name);
    }
    println!();
    println!("First candidate rows after prefixing:");

    for row in 0..table.row_count.min(5) {
        let length = table.column("xdp.length").unwrap().values[row];
        let gm = table.column("xdp.gm").unwrap().values[row];
        let ro = table.column("xdp.Ro").unwrap().values[row];
        let gain_proxy = table.column("gain_proxy").unwrap().values[row];

        println!(
            "row={row} length={length:.3e} gm={gm:.3e} Ro={ro:.3e} gain_proxy={gain_proxy:.3e}"
        );
    }

    Ok(())
}
