[package]
name = "sstadex-gui"
version.workspace = true
license.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
libsstadex = { path = "../libsstadex", default-features = false }
eframe = "0.32"
egui = "0.32"
